In [2]:
import pandas as pd
import numpy as np

In [3]:
movie=pd.read_csv("IMDB Dataset.csv")

In [4]:
movie.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
movie['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [6]:
movie.shape

(50000, 2)

# Text Cleaning
## 1.Sample 10000 rows
## 2.Remove html tags
## 3.Remove special characters
## 4.Convert every thing to lower case
## 5.Removing stop words
## 6.Stemming

In [7]:
movie=movie.sample(10000)

In [8]:
movie.shape

(10000, 2)

In [9]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 28644 to 10213
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [10]:
movie['sentiment'].replace({'positive':1,'negative':0},inplace=True)

/var/folders/pq/zvryn37d24d_gy1ym8p3blzc0000gn/T/ipykernel_44383/1544908436.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie['sentiment'].replace({'positive':1,'negative':0},inplace=True)
/var/folders/pq/zvryn37d24d_gy1ym8p3blzc0000gn/T/ipykernel_44383/1544908436.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  movie['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [11]:
movie.head()

                                                  review  sentiment
28644  Du Rififi Chez Les Hommes/Rififi(1955) can on ...          1
22192  The Lady From Shanghai is weird even by the st...          1
16272  This is an excellent documentary, packed with ...          1
49958  As someone who loves baseball history, especia...          0
44848  I only lasted 15mins before self preservation ...          0

In [12]:
import re
clean=re.compile('<.*?>')
re.sub(clean,'',movie.iloc[2].review)

'This is an excellent documentary, packed with racing action beautiful pictures and a great story. The IMAX Cameras give you a very wide perspective, as a DVD movie it is perfect. Your hear every speaker working almost all the time, The film is not speeded up and just gives you the natural feel of 230mph. Of course there are some sound effects added but i think they are good, they give a depth to the driving scenes...'

In [13]:
# Function to clean html tags
def clean_html(text):
    clean=re.compile('<.*?>')
    return re.sub(clean,'',text)

In [14]:
movie['review']=movie['review'].apply(clean_html)

In [15]:
# Converting everything to lowercase
def convert_lower(text):
    return text.lower()

In [16]:
movie['review']=movie['review'].apply(convert_lower)

In [17]:
movie.head()

                                                  review  sentiment
28644  du rififi chez les hommes/rififi(1955) can on ...          1
22192  the lady from shanghai is weird even by the st...          1
16272  this is an excellent documentary, packed with ...          1
49958  as someone who loves baseball history, especia...          0
44848  i only lasted 15mins before self preservation ...          0

In [18]:
# Function to remove special characters
def remove_special(text):
    x=''

    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' '
    return x

In [19]:
movie['review']=movie['review'].apply(remove_special)

In [27]:
#Remove the stop words
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nishita/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [28]:
from nltk.corpus import stopwords

In [29]:
# Remove the stop words
def remove_stopwords(text):
    x=[]
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear
    return y

In [30]:
movie['review']=movie['review'].apply(remove_stopwords)

In [31]:
movie

                                                  review  sentiment
28644  [du, rififi, chez, les, hommes, rififi, 1955, ...          1
22192  [lady, shanghai, weird, even, standards, emine...          1
16272  [excellent, documentary, packed, racing, actio...          1
49958  [someone, loves, baseball, history, especially...          0
44848  [lasted, 15mins, self, preservation, jerked, e...          0
...                                                  ...        ...
1113   [nice, movie, entire, family, watch, together,...          1
35174  [also, endured, hundreds, children, movies, pa...          0
29473  [love, sharks, mutants, explosions, theoretica...          0
15170  [seen, film, 3, times, mostly, kept, thinking,...          0
10213  [home, room, like, zero, day, elephant, inspir...          1

[10000 rows x 2 columns]

In [32]:
# Stemming
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [33]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [34]:
movie['review']=movie['review'].apply(stem_words)

In [35]:
# Join back
def join_back(list_input):
    return " ".join(list_input)

In [36]:
movie['review']=movie['review'].apply(join_back)

In [37]:
movie

                                                  review  sentiment
28644  du rififi chez le homm rififi 1955 surfac desc...          1
22192  ladi shanghai weird even standard emin directo...          1
16272  excel documentari pack race action beauti pict...          1
49958  someon love basebal histori especi earli 20th ...          0
44848  last 15min self preserv jerk empti eye drool s...          0
...                                                  ...        ...
1113   nice movi entir famili watch togeth josi bisse...          1
35174  also endur hundr children movi past consid one...          0
29473  love shark mutant explos theoret paramet mind ...          0
15170  seen film 3 time mostli kept think watch miss ...          0
10213  home room like zero day eleph inspir recent wa...          1

[10000 rows x 2 columns]

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=10000)

In [54]:
X=cv.fit_transform(movie['review']).toarray()

In [55]:
X.shape

(10000, 10000)

In [56]:
y=movie.iloc[:,-1].values

In [57]:
y.shape

(10000,)

In [58]:
# splitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [59]:
x_train.shape

(8000, 10000)

In [60]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [61]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [62]:
clf1.fit(x_train,y_train)
clf2.fit(x_train,y_train)
clf3.fit(x_train,y_train)

BernoulliNB()

In [63]:
y_pred1=clf1.predict(x_test)
y_pred2=clf2.predict(x_test)
y_pred3=clf3.predict(x_test)

In [64]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred1))
print(accuracy_score(y_test,y_pred2))
print(accuracy_score(y_test,y_pred3))

0.6515
0.8495
0.8405

In [65]:
import os
print(os.getcwd())

/Users/nishita/Desktop/machine learning/sentiment-analysis-using-Naive-bayes